# Generated by Django 4.1.3 on 2023-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancelAttendance', '0002_remove_leavereq_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereq',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=256),
        ),
    ]
