# Generated by Django 4.1.3 on 2023-03-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancelAttendance', '0003_leavereq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereq',
            name='Attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
